#!/bin/bash
#
LINE=$(awk -F" " 'BEGIN{ OFS=":"}{
  print $1,$2,$3,$4,$5,$6,$7
}' "OneStar.txt")

echo $LINE

IFS=: read NAME RAh RAm RAs DECd DECm DECs <<< "$LINE"

echo $NAME
echo $RAh
echo $RAm
echo $RAs
echo $DECd
echo $DECm
echo $DECs


./fitsfileIOscript.exe $NAME $RAh $RAm $RAs $DECd $DECm $DECs